name: 'jaffle_shop'
version: '1.0.0'
config-version: 2
require-dbt-version: [">=0.17.0"]

#profile: 'my-databricks'

profile: 'jaffle_shop'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
