jaffle_shop:
  target: databricks_job
  outputs:
    databricks_job:
      type: databricks
      method: http
      schema: default
      host: adb-7210415297556310.10.azuredatabricks.net
      http_path: sql/protocolv1/o/7210415297556310/0103-140847-id7299gw
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
